-- Migracion base del esquema `inventario`, extraida de docs/db/schema.sql
-- (monolito original) al dividir por servicio propietario.
--
-- NOTA: `inventario.inventario_producto` ya incluye aqui las columnas
-- (nombre, costo, precio_referencia, habilitado) que la migracion V004
-- original (docs/db/migrations/V004__inventario_propietario_stock.sql)
-- agregaba via ALTER TABLE -- porque docs/db/schema.sql, pese a nunca
-- haberse aplicado por un motor de migraciones, ya se mantenia a mano
-- reflejando el resultado final de V004. Ver el documento de cierre de
-- este punto para la decision sobre que hacer con el resto de V004
-- (el backfill de datos cruzado hacia `productos`, que no se traslada
-- aqui) y con V005/V006 (ya reflejadas en el monolito, no se recrean).

CREATE SCHEMA IF NOT EXISTS inventario;

CREATE TABLE IF NOT EXISTS inventario.tipo_movimiento (
    tipo_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    CONSTRAINT pk_tipo_movimiento PRIMARY KEY (tipo_id),
    CONSTRAINT uq_tipo_movimiento_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS inventario.subtipo_movimiento (
    subtipo_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    tipo_id INT8 NOT NULL,
    CONSTRAINT pk_subtipo_movimiento PRIMARY KEY (subtipo_id),
    CONSTRAINT uq_subtipo_movimiento_nombre UNIQUE (nombre),
    CONSTRAINT fk_subtipo_tipo FOREIGN KEY (tipo_id)
        REFERENCES inventario.tipo_movimiento (tipo_id)
);

CREATE TABLE IF NOT EXISTS inventario.inventario_producto (
    producto_id INT8 NOT NULL,
    nombre STRING NOT NULL,
    stock INT4 NOT NULL DEFAULT 0,
    stock_minimo INT4 NOT NULL DEFAULT 0,
    costo DECIMAL(18,2) NOT NULL DEFAULT 0,
    precio_referencia DECIMAL(18,2) NOT NULL DEFAULT 0,
    habilitado BOOL NOT NULL DEFAULT true,
    valor_inventario DECIMAL(18,2) NOT NULL DEFAULT 0,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_inventario_producto PRIMARY KEY (producto_id),
    CONSTRAINT ck_inventario_stock CHECK (stock >= 0),
    CONSTRAINT ck_inventario_costo CHECK (costo >= 0)
);

CREATE TABLE IF NOT EXISTS inventario.movimiento_inventario (
    movimiento_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
    cantidad INT4 NOT NULL,
    costo_unitario DECIMAL(18,2),
    costo_total DECIMAL(18,2),
    referencia STRING,
    observacion STRING,
    producto_id INT8 NOT NULL,
    subtipo_id INT8 NOT NULL,
    CONSTRAINT pk_movimiento_inventario PRIMARY KEY (movimiento_id),
    CONSTRAINT fk_movimiento_subtipo FOREIGN KEY (subtipo_id)
        REFERENCES inventario.subtipo_movimiento (subtipo_id),
    INDEX idx_movimiento_producto_fecha (producto_id, fecha DESC)
);

CREATE TABLE IF NOT EXISTS inventario.solicitud_idempotente (
    clave VARCHAR(200) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_solicitud_idempotente PRIMARY KEY (clave)
);

CREATE TABLE IF NOT EXISTS inventario.kardex_inventario (
    kardex_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
    tipo_operacion STRING NOT NULL,
    cantidad_entrada INT4 NOT NULL DEFAULT 0,
    costo_unitario_entrada DECIMAL(18,2),
    costo_total_entrada DECIMAL(18,2),
    cantidad_salida INT4 NOT NULL DEFAULT 0,
    costo_unitario_salida DECIMAL(18,2),
    costo_total_salida DECIMAL(18,2),
    saldo_cantidad INT4 NOT NULL,
    saldo_costo_unitario DECIMAL(18,2) NOT NULL,
    saldo_total DECIMAL(18,2) NOT NULL,
    producto_id INT8 NOT NULL,
    CONSTRAINT pk_kardex_inventario PRIMARY KEY (kardex_id),
    INDEX idx_kardex_producto_fecha (producto_id, fecha DESC)
);
