-- Migracion base del esquema `ventas`, extraida de docs/db/schema.sql
-- (monolito original) al dividir por servicio propietario. Contenido
-- identico al de esa fuente para las tablas de este esquema.

CREATE SCHEMA IF NOT EXISTS ventas;

CREATE TABLE IF NOT EXISTS ventas.factura_encabezado (
    factura_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_id INT8 NOT NULL,
    fecha_orden DATE NOT NULL,
    usuario_id INT8 NOT NULL,
    fecha_emision DATE NOT NULL DEFAULT current_date(),
    cedula STRING,
    nombre STRING,
    correo STRING,
    telefono STRING,
    direccion_entrega STRING,
    subtotal DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    numero STRING NOT NULL,
    CONSTRAINT pk_factura PRIMARY KEY (factura_id),
    CONSTRAINT uq_factura_orden UNIQUE (orden_id),
    CONSTRAINT uq_factura_numero UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS ventas.factura_cuerpo (
    factura_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    nombre_producto STRING NOT NULL,
    cantidad INT4 NOT NULL,
    precio DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    iva DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_factura_cuerpo PRIMARY KEY (factura_id, producto_id),
    CONSTRAINT fk_factura_cuerpo
        FOREIGN KEY (factura_id)
        REFERENCES ventas.factura_encabezado (factura_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ventas.factura_outbox (
    evento_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    factura_id INT8 NOT NULL,
    estado STRING NOT NULL DEFAULT 'PENDIENTE',
    intentos INT4 NOT NULL DEFAULT 0,
    ultimo_error STRING,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    procesado_en TIMESTAMPTZ,
    CONSTRAINT pk_factura_outbox PRIMARY KEY (evento_id),
    CONSTRAINT uq_factura_outbox_factura UNIQUE (factura_id),
    CONSTRAINT fk_factura_outbox_factura
        FOREIGN KEY (factura_id) REFERENCES ventas.factura_encabezado (factura_id),
    CONSTRAINT ck_factura_outbox_estado CHECK (estado IN ('PENDIENTE', 'PROCESADO', 'FALLIDO')),
    INDEX idx_factura_outbox_estado (estado, creado_en)
);
