-- Migracion base del esquema `pedidos`, extraida de docs/db/schema.sql
-- (monolito original) al dividir por servicio propietario. Contenido
-- identico al de esa fuente para las tablas de este esquema.

CREATE SCHEMA IF NOT EXISTS pedidos;

-- `fecha` encabeza la PK porque CockroachDB requiere que las columnas de
-- particionamiento formen un prefijo de la clave primaria.
CREATE TABLE IF NOT EXISTS pedidos.orden (
    fecha DATE NOT NULL,
    orden_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT8 NOT NULL,
    direccion_id INT8,
    metodopago_id INT8,
    subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    estado STRING NOT NULL DEFAULT 'CREADA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_orden PRIMARY KEY (fecha, orden_id),
    CONSTRAINT ck_orden_total_no_negativo CHECK (total >= 0),
    UNIQUE INDEX uq_orden_id (orden_id),
    INDEX idx_orden_usuario_fecha (usuario_id, fecha DESC)
        STORING (estado, total)
);

-- El dataset analitico usa los IDs 1..600000. La secuencia avanza desde el
-- mayor ID existente o desde 1000000, sin retroceder al reaplicar el esquema.
SELECT setval(
    'pedidos.orden_orden_id_seq',
    greatest(coalesce((SELECT max(orden_id) FROM pedidos.orden), 0), 1000000)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_orden_id ON pedidos.orden (orden_id);

CREATE TABLE IF NOT EXISTS pedidos.carrito_de_compra (
    carrito_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT8 NOT NULL,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    habilitado BOOL NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_carrito PRIMARY KEY (carrito_id),
    INDEX idx_carrito_usuario_habilitado (usuario_id, habilitado)
);

CREATE TABLE IF NOT EXISTS pedidos.carrito_detalle (
    carrito_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad INT4 NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_carrito_detalle PRIMARY KEY (carrito_id, producto_id),
    CONSTRAINT fk_carrito_detalle
        FOREIGN KEY (carrito_id)
        REFERENCES pedidos.carrito_de_compra (carrito_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_carrito_cantidad_positiva CHECK (cantidad > 0)
);

CREATE TABLE IF NOT EXISTS pedidos.tipo_metodopago (
    tipo_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_metodopago PRIMARY KEY (tipo_id),
    CONSTRAINT uq_tipo_metodopago_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS pedidos.metodopago (
    metodopago_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    numero_tarjeta STRING,
    fecha_expiracion DATE,
    habilitado BOOL NOT NULL DEFAULT true,
    tipo_id INT8 NOT NULL,
    usuario_id INT8 NOT NULL,
    CONSTRAINT pk_metodopago PRIMARY KEY (metodopago_id),
    CONSTRAINT fk_metodopago_tipo
        FOREIGN KEY (tipo_id) REFERENCES pedidos.tipo_metodopago (tipo_id),
    INDEX idx_metodopago_usuario (usuario_id, habilitado)
);

-- Fila aislada para demostrar de forma controlada una colision SERIALIZABLE.
-- No participa en el flujo funcional ni altera datos de negocio.
CREATE TABLE IF NOT EXISTS pedidos.retry_probe (
    probe_id INT8 NOT NULL,
    valor INT8 NOT NULL DEFAULT 0,
    CONSTRAINT pk_retry_probe PRIMARY KEY (probe_id)
);
UPSERT INTO pedidos.retry_probe (probe_id, valor) VALUES (1, 0);

CREATE TABLE IF NOT EXISTS pedidos.detalle_orden (
    fecha DATE NOT NULL,
    detalle_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad INT4 NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    iva DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_detalle_orden PRIMARY KEY (fecha, detalle_id),
    CONSTRAINT fk_detalle_orden
        FOREIGN KEY (fecha, orden_id)
        REFERENCES pedidos.orden (fecha, orden_id),
    CONSTRAINT ck_detalle_cantidad_positiva CHECK (cantidad > 0),
    INDEX idx_detalle_orden (fecha, orden_id),
    INDEX idx_detalle_producto_fecha (producto_id, fecha DESC)
);

CREATE TABLE IF NOT EXISTS pedidos.solicitud_idempotente (
     usuario_id    INT8        NOT NULL,
     clave         VARCHAR     NOT NULL,
     payload_hash  VARCHAR     NOT NULL,
     orden_id      INT8        NOT NULL,
     creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_solicitud_idempotente PRIMARY KEY (usuario_id, clave),
    CONSTRAINT fk_solicitud_idempotente_orden
    FOREIGN KEY (orden_id) REFERENCES pedidos.orden (orden_id)
);
