import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../services/api'
import { addToCart } from '../services/cart'
import { getUser } from '../services/session'
import { field, imageFallback, money, Row } from './shared'
interface Category { key:string; id:number; name:string; short:string; required:boolean }
interface Product { id:number; name:string; price:number; image:string; brand:string }
interface Component { id:number; nombre:string; precio:number }
interface Recommendation { presupuestoUsado:number; componentes:Record<string,Component>; porcentajeCuelloBotella:number|null; nivelCuelloBotella:string|null; componenteLimitante:string|null; advertencias:string[] }
interface Analysis { porcentajeCuelloBotella:number; nivel:string; componenteLimitante:string; explicacion:string; advertencias:string[]; recomendacion:Recommendation|null }
const STORAGE_KEY='pcbuilder.selection'
const categories:Category[]=[{key:'cpu',id:2,name:'Procesador',short:'CPU',required:true},{key:'mobo',id:8,name:'Motherboard',short:'MB',required:true},{key:'ram',id:7,name:'Memoria RAM',short:'RAM',required:true},{key:'storage',id:1,name:'Almacenamiento',short:'SSD',required:true},{key:'gpu',id:6,name:'Tarjeta gráfica',short:'GPU',required:false},{key:'psu',id:5,name:'Fuente de poder',short:'PSU',required:true},{key:'case',id:4,name:'Gabinete',short:'CASE',required:true},{key:'cooling',id:3,name:'Refrigeración',short:'COOL',required:false},{key:'periferico',id:9,name:'Periféricos',short:'I/O',required:false}]
const normalize=(row:Row):Product=>{const imageId=field(row,'imagenId','imagen_id','portadaId','portada_id','galeriaId','galeria_id');return{id:Number(field(row,'id','productoId','producto_id','id_producto')||0),name:String(field(row,'nombre','producto')||'Producto'),price:Number(field(row,'precio','preciounitario','precioUnitario','costo')||0),image:imageId?`/api/galeria_v2/img/${imageId}`:'/assets/placeholder.svg',brand:String(field(row,'marca','nombre_marca')||'')}}
const levelClass=(level?:string|null)=>level==='SEVERO'?'severo':level==='MODERADO'?'moderado':level==='EQUILIBRADO'?'equilibrado':'neutral'
const invalidBudget=(value:number|null)=>value!==null&&(!Number.isFinite(value)||value<=0)
export default function BuilderView(){
 const navigate=useNavigate(),[active,setActive]=useState(categories[0]),[products,setProducts]=useState<Product[]>([]),[selection,setSelection]=useState<Record<string,Product>>(()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{}}catch{return{}}}),[loading,setLoading]=useState(false),[adding,setAdding]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[budget,setBudget]=useState(''),[analyzing,setAnalyzing]=useState(false),[analyzeError,setAnalyzeError]=useState(''),[analysis,setAnalysis]=useState<Analysis|null>(null),[previous,setPrevious]=useState<Record<string,Product>|null>(null)
 const total=useMemo(()=>Object.values(selection).reduce((sum,p)=>sum+p.price,0),[selection]),count=Object.keys(selection).length,completed=categories.filter(c=>c.required).every(c=>selection[c.key]),canApply=!!analysis?.recomendacion&&analysis.recomendacion.porcentajeCuelloBotella!==null
 const store=(next:Record<string,Product>)=>{setSelection(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))},invalidate=()=>{setAnalysis(null);setPrevious(null)}
 const loadCategory=async(category:Category)=>{setActive(category);setLoading(true);setError('');try{setProducts((await api<Row[]>(`/api/productos/por-categoria?categoriaId=${category.id}`)).map(normalize).filter(p=>p.id>0))}catch(cause){setProducts([]);setError(cause instanceof Error?cause.message:'No se pudieron cargar los componentes.')}finally{setLoading(false)}}
 useEffect(()=>{void loadCategory(categories[0])},[])
 const select=(product:Product)=>{store({...selection,[active.key]:product});setNotice(`${product.name} añadido a la configuración.`);setTimeout(()=>setNotice(''),2200);invalidate()}
 const remove=(key:string)=>{const next={...selection};delete next[key];store(next);invalidate()}
 const clear=()=>{setSelection({});localStorage.removeItem(STORAGE_KEY);invalidate()}
 const addBuild=async()=>{if(!getUser()){navigate('/login?next=%2Farmado');return}setAdding(true);setError('');try{for(const product of Object.values(selection))await addToCart(product.id,1);setNotice('Configuración añadida al carrito.')}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo añadir la configuración.')}finally{setAdding(false)}}
 const runAnalysis=async()=>{if(!selection.cpu||analyzing)return;const raw=budget.trim().replace(/\s+/g,'').replace(',','.');const parsed=raw?Number(raw):null;if(invalidBudget(parsed)){setAnalyzeError('El presupuesto debe ser un número positivo (ej. 1200 o 1200.50).');setAnalysis(null);return}setAnalyzing(true);setAnalyzeError('');setAnalysis(null);setPrevious(null);try{const body:Record<string,unknown>={componentes:Object.fromEntries(categories.map(c=>[c.key,selection[c.key]?.id??null]))};if(parsed!==null)body.presupuestoMaximo=parsed;setAnalysis(await api<Analysis>('/api/armado/analizar',{method:'POST',body:JSON.stringify(body)}))}catch(cause){setAnalyzeError(cause instanceof Error?cause.message:'No se pudo analizar la configuración.')}finally{setAnalyzing(false)}}
 const apply=()=>{const recommendation=analysis?.recomendacion;if(!recommendation||!canApply)return;setPrevious({...selection});const next={...selection};Object.entries(recommendation.componentes).forEach(([key,c])=>next[key]={id:c.id,name:c.nombre,price:c.precio,image:'/assets/placeholder.svg',brand:''});store(next);setNotice('Recomendación aplicada a tu configuración.')}
 const restore=()=>{if(!previous)return;store({...previous});setPrevious(null);setNotice('Se restauró tu configuración anterior.')}
 const renderBuildSummary = () => (<aside className="build-summary"><p className="eyebrow">Resumen</p><h2>Tu equipo</h2><div className="summary-lines">{categories.filter(c=>selection[c.key]).map(c=><p key={c.key}><span>{c.short}<small>{selection[c.key].name}</small></span><strong>{money(selection[c.key].price)}</strong></p>)}</div>{!count&&<p className="summary-placeholder">Selecciona componentes para calcular tu configuración.</p>}<div className="build-total"><span>Total estimado</span><strong>{money(total)}</strong></div><button className="button" disabled={!count||adding} onClick={()=>void addBuild()}>{adding?'Añadiendo…':'Añadir al carrito'}</button><small className={completed?'complete':''}>{completed?'✓ Configuración esencial completa':'Completa los componentes requeridos'}</small></aside>);
 const renderAnalysis = () => (<section className="armado-analysis"><div className="armado-analysis-head"><div><p className="eyebrow">Análisis con IA</p><h2>¿Qué tan equilibrada está tu configuración?</h2><p className="armado-hint">Es solo informativo: no bloquea la compra.</p></div><div className="armado-controls"><label>Presupuesto (opcional)<input type="text" inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Ej. 1200"/></label><button className="button" disabled={!selection.cpu||analyzing} onClick={()=>void runAnalysis()}>{analyzing?'Analizando…':'Analizar mi configuración'}</button></div></div>{!selection.cpu&&<p className="armado-hint">Elegí al menos un procesador para poder analizar.</p>}{analyzeError&&<p className="alert">{analyzeError}</p>}{analysis&&<div className="armado-result"><div className={`armado-score ${levelClass(analysis.nivel)}`}><strong>{analysis.porcentajeCuelloBotella}%</strong><span>{analysis.nivel}</span></div><div className="armado-detail"><p><strong>Componente limitante:</strong> {analysis.componenteLimitante}</p><p className="armado-explicacion">{analysis.explicacion}</p>{analysis.advertencias.length>0&&<ul className="armado-warnings">{analysis.advertencias.map((warning,index)=><li key={index}>{warning}</li>)}</ul>}</div>{analysis.recomendacion&&renderRecommendation()}</div>}</section>);
 const renderRecommendation = () => analysis?.recomendacion && (<div className="armado-recommendation"><h3>Configuración recomendada</h3><ul className="armado-rec-items">{Object.entries(analysis.recomendacion.componentes).map(([key,c])=><li key={key}><span>{categories.find(x=>x.key===key)?.name||key}</span><strong>{c.nombre}</strong><small>{money(c.precio)}</small></li>)}</ul><div className="armado-rec-footer"><span>Total: <strong>{money(analysis.recomendacion.presupuestoUsado)}</strong></span>{analysis.recomendacion.porcentajeCuelloBotella!==null&&<span>Cuello de botella resultante: <strong className={levelClass(analysis.recomendacion.nivelCuelloBotella)}>{analysis.recomendacion.porcentajeCuelloBotella}%</strong></span>}</div>{analysis.recomendacion.advertencias.length>0&&<ul className="armado-warnings">{analysis.recomendacion.advertencias.map((w,i)=><li key={i}>{w}</li>)}</ul>}{canApply?<div className="armado-rec-actions"><button className="button" onClick={apply}>Aplicar esta recomendación</button>{previous&&<button className="secondary-button" onClick={restore}>Volver a mi configuración</button>}</div>:<p className="armado-hint armado-no-mejora">No se encontró una configuración que mejore el rendimiento dentro de este presupuesto.</p>}</div>);
 return <section className="builder-page"><header className="builder-hero"><div><p className="eyebrow">PC Builder</p><h1>Arma el equipo<br/><em>perfecto para ti.</em></h1><p>Selecciona cada componente y guarda tu configuración en el carrito.</p></div><div className="build-progress"><strong>{count}/{categories.length}</strong><span>componentes elegidos</span><div><i style={{width:`${count/categories.length*100}%`}}/></div></div></header>
 <div className="builder-layout"><aside className="builder-slots"><div className="builder-title"><div><p className="eyebrow">Configuración</p><h2>Componentes</h2></div>{count>0&&<button onClick={clear}>Limpiar</button>}</div>{categories.map(category=><button key={category.key} className={`builder-slot${active.key===category.key?' active':''}${selection[category.key]?' selected':''}`} onClick={()=>void loadCategory(category)}><span className="slot-icon">{category.short}</span><span><strong>{category.name}</strong><small>{selection[category.key]?.name||(category.required?'Requerido':'Opcional')}</small></span>{selection[category.key]?<b onClick={e=>{e.stopPropagation();remove(category.key)}}>×</b>:<i>›</i>}</button>)}</aside>
 <main className="builder-products"><div className="builder-products-head"><div><p className="eyebrow">Seleccionar</p><h2>{active.name}</h2></div><span>{products.length} opciones</span></div>{loading?<p className="status">Buscando componentes…</p>:error?<p className="alert">{error}</p>:products.length?<div className="builder-grid">{products.map(product=><article key={product.id} className={selection[active.key]?.id===product.id?'chosen':''}><img src={product.image} alt={product.name} onError={imageFallback}/><div><small>{product.brand||active.name}</small><h3>{product.name}</h3><strong>{money(product.price)}</strong><div className="builder-card-actions"><Link to={`/producto/${product.id}`}>Detalles</Link><button onClick={()=>select(product)}>{selection[active.key]?.id===product.id?'Seleccionado':'Elegir'}</button></div></div></article>)}</div>:<div className="builder-empty"><span>⌁</span><h3>No hay {active.name.toLowerCase()} en CRDB</h3><p>La interfaz está lista; aparecerán aquí cuando se cree el catálogo distribuido.</p></div>}</main>
 {renderBuildSummary()}</div>
 {renderAnalysis()}{notice&&<p className="builder-toast">{notice}</p>}</section>
}
