import { FormEvent, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { api, ApiError } from '../services/api'
import { isAdmin, saveSession, SessionUser } from '../services/session'

interface LoginResponse { user?: SessionUser; usuario?: SessionUser; token?: string; access?: string; accessToken?: string; message?: string }
function loginToken(data: LoginResponse) { return data.token || data.access || data.accessToken }
export default function LoginView({ onSessionChanged }: { onSessionChanged: () => void }) {
  const navigate = useNavigate(), location = useLocation(), [usuario, setUsuario] = useState(''), [contrasena, setContrasena] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { const data = await api<LoginResponse>('/api/login', { method: 'POST', body: JSON.stringify({ usuario: usuario.trim(), contrasena, contrasenia: contrasena, password: contrasena }) }); const user = data.user || data.usuario; if (!user) throw new ApiError(data.message || 'La respuesta no contiene un usuario.', 422); saveSession(user, loginToken(data)); onSessionChanged(); const next = new URLSearchParams(location.search).get('next'); navigate(next || (isAdmin(user) ? '/admin' : '/')) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible iniciar sesión.') } finally { setBusy(false) } }
  const inactive = new URLSearchParams(location.search).get('reason') === 'inactive'
  return <section className="login-page"><div className="login-art" aria-hidden="true"><span>Tu próximo equipo<br />empieza aquí.</span></div><form className="login-card" onSubmit={submit}><p className="eyebrow">Bienvenido de vuelta</p><h1>Inicia sesión</h1><p className="muted">Accede a tu carrito, pedidos y configuraciones.</p>{inactive&&<p className="alert" role="status">Tu sesión se cerró por inactividad.</p>}<label>Usuario<input value={usuario} onChange={(e) => setUsuario(e.target.value)} autoComplete="username" required placeholder="Ingresa tu usuario" /></label><label>Contraseña<input value={contrasena} onChange={(e) => setContrasena(e.target.value)} type="password" autoComplete="current-password" required placeholder="Ingresa tu contraseña" /></label>{error && <p className="alert" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy ? 'Validando…' : 'Entrar'}</button><div className="form-links"><Link to="/registro">Crear cuenta</Link><Link to="/recuperacion">Olvidé mi contraseña</Link></div></form></section>
}
