import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../services/api'
import { addToCart } from '../services/cart'
import { getUser } from '../services/session'
import { field, imageFallback, money, productId, productImage, productName, productPrice, Row } from './shared'

export default function ProductDetailView() {
  const { id: rawId } = useParams(), id = Number(rawId), navigate = useNavigate()
  const [product, setProduct] = useState<Row | null>(null), [gallery, setGallery] = useState<Row[]>([]), [activeImage, setActiveImage] = useState(''), [quantity, setQuantity] = useState(1), [loading, setLoading] = useState(true), [adding, setAdding] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  useEffect(() => { void (async () => { if (!Number.isInteger(id) || id <= 0) { setError('Producto inválido.'); setLoading(false); return } try { const found = await api<Row>(`/api/productos/${id}`).catch(async () => (await api<Row[]>('/api/productos?size=200')).find((row) => productId(row) === id) || null); if (!found) throw new Error('Producto no encontrado.'); setProduct(found); const images = await api<Row[]>(`/api/galeria_v2/producto/${id}?scope=galeria`).catch(() => []); setGallery(images); setActiveImage(images.length ? productImage(images[0]) : productImage(found)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar el producto.') } finally { setLoading(false) } })() }, [id])
  const add = async () => { setNotice(''); if (!getUser()) { navigate(`/login?next=${encodeURIComponent(`/producto/${id}`)}`); return } setAdding(true); try { await addToCart(id, quantity); setNotice('Producto añadido al carrito.') } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo añadir el producto.') } finally { setAdding(false) } }
  const renderProductInfo = () => product && (<div className="detail-info"><p className="eyebrow">{String(field(product, 'categoria', 'categoria_nombre', 'nombre_categoria') || 'Componente')}</p><h1>{productName(product)}</h1><p className="detail-description">{String(field(product, 'descripcion', 'detalle') || 'Componente disponible en TiendaTech.')}</p><strong className="detail-price">{money(productPrice(product))}</strong><div className="buy-row"><label>Cantidad<input value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} type="number" min="1" max="99" /></label><button className="button" disabled={adding} onClick={add}>{adding ? 'Añadiendo…' : 'Añadir al carrito'}</button></div>{notice && <p className="success">{notice} <Link to="/carrito">Ver carrito</Link></p>}{error && <p className="alert">{error}</p>}<ul className="benefits"><li>✓ Compra protegida</li><li>✓ Inventario actualizado</li><li>✓ Atención especializada</li></ul></div>);
 return <section className="detail-wrap"><Link className="back-link" to="/">← Volver al catálogo</Link>{loading ? <p className="status">Cargando producto…</p> : error && !product ? <p className="alert">{error}</p> : product && <div className="detail-grid"><div className="gallery-panel"><img className="detail-image" src={activeImage} alt={productName(product)} onError={imageFallback} />{gallery.length > 1 && <div className="thumbnails">{gallery.map((item, index) => <button key={index} onClick={() => setActiveImage(productImage(item))}><img src={productImage(item)} alt="" /></button>)}</div>}</div>{renderProductInfo()}</div>}</section>
}
