-- Migracion base del esquema `ordenes_proveedores`, extraida de
-- docs/db/schema.sql (monolito original) al dividir por servicio
-- propietario. Contenido identico al de esa fuente para las tablas de
-- este esquema.

CREATE SCHEMA IF NOT EXISTS ordenes_proveedores;

CREATE TABLE IF NOT EXISTS ordenes_proveedores.proveedor (
    proveedor_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    ruc STRING NOT NULL,
    contacto_nombre STRING,
    telefono STRING,
    correo STRING,
    direccion STRING,
    activo BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_proveedor PRIMARY KEY (proveedor_id),
    CONSTRAINT uq_proveedor_ruc UNIQUE (ruc)
);

CREATE TABLE IF NOT EXISTS ordenes_proveedores.orden_compra (
    orden_compra_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    proveedor_id INT8 NOT NULL,
    usuario_id INT8 NOT NULL,
    numero_orden STRING UNIQUE,
    fecha_emision DATE NOT NULL DEFAULT current_date(),
    fecha_esperada DATE,
    fecha_recepcion DATE,
    estado STRING NOT NULL DEFAULT 'PENDIENTE',
    subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    iva DECIMAL(18,2) NOT NULL DEFAULT 0,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_orden_compra PRIMARY KEY (orden_compra_id),
    CONSTRAINT fk_orden_compra_proveedor FOREIGN KEY (proveedor_id)
        REFERENCES ordenes_proveedores.proveedor (proveedor_id),
    CONSTRAINT ck_orden_compra_estado CHECK (estado IN
        ('PENDIENTE', 'ENVIADA', 'RECIBIDA_PARCIAL', 'RECIBIDA', 'CANCELADA')),
    INDEX idx_orden_compra_estado_fecha (estado, fecha_emision DESC)
);

CREATE TABLE IF NOT EXISTS ordenes_proveedores.detalle_orden_compra (
    detalle_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_compra_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad_pedida INT4 NOT NULL,
    cantidad_recibida INT4 NOT NULL DEFAULT 0,
    costo_unitario DECIMAL(18,2) NOT NULL,
    subtotal_linea DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_detalle_orden_compra PRIMARY KEY (detalle_id),
    CONSTRAINT uq_detalle_orden_producto UNIQUE (orden_compra_id, producto_id),
    CONSTRAINT fk_detalle_orden FOREIGN KEY (orden_compra_id)
        REFERENCES ordenes_proveedores.orden_compra (orden_compra_id) ON DELETE CASCADE,
    CONSTRAINT ck_detalle_cantidad CHECK (cantidad_pedida > 0),
    CONSTRAINT ck_detalle_recibida CHECK
        (cantidad_recibida >= 0 AND cantidad_recibida <= cantidad_pedida),
    CONSTRAINT ck_detalle_costo CHECK (costo_unitario >= 0)
);
