-- TiendaTech - esquema distribuido para CockroachDB 23.2+
-- Entrega 3 / Modulo B
--
-- Patron dominante:
--   1. consultas de pedidos por trimestre;
--   2. historial de pedidos por usuario;
--   3. lectura conjunta de encabezado y detalle.
--
-- La columna `fecha` del modelo implementado corresponde a `fecha_pedido`
-- en la guia de la Entrega 3.

CREATE DATABASE IF NOT EXISTS tiendatech;
USE tiendatech;

CREATE SCHEMA IF NOT EXISTS usuarios;
CREATE SCHEMA IF NOT EXISTS pedidos;
CREATE SCHEMA IF NOT EXISTS ventas;
CREATE SCHEMA IF NOT EXISTS productos;
CREATE SCHEMA IF NOT EXISTS inventario;
CREATE SCHEMA IF NOT EXISTS ordenes_proveedores;

CREATE TABLE IF NOT EXISTS usuarios.usuario (
    usuario_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    correo STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_correo UNIQUE (correo)
);

-- `fecha` encabeza la PK porque CockroachDB requiere que las columnas de
-- particionamiento formen un prefijo de la clave primaria.
CREATE TABLE IF NOT EXISTS pedidos.orden (
    fecha DATE NOT NULL,
    orden_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT8 NOT NULL,
    direccion_id INT8,
    metodopago_id INT8,
    subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    estado STRING NOT NULL DEFAULT 'CREADA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_orden PRIMARY KEY (fecha, orden_id),
    CONSTRAINT ck_orden_total_no_negativo CHECK (total >= 0),
    UNIQUE INDEX uq_orden_id (orden_id),
    INDEX idx_orden_usuario_fecha (usuario_id, fecha DESC)
        STORING (estado, total)
);

-- El dataset analitico usa los IDs 1..600000. La secuencia avanza desde el
-- mayor ID existente o desde 1000000, sin retroceder al reaplicar el esquema.
SELECT setval(
    'pedidos.orden_orden_id_seq',
    greatest(coalesce((SELECT max(orden_id) FROM pedidos.orden), 0), 1000000)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_orden_id ON pedidos.orden (orden_id);

CREATE TABLE IF NOT EXISTS pedidos.carrito_de_compra (
    carrito_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT8 NOT NULL,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    habilitado BOOL NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_carrito PRIMARY KEY (carrito_id),
    INDEX idx_carrito_usuario_habilitado (usuario_id, habilitado)
);

CREATE TABLE IF NOT EXISTS pedidos.carrito_detalle (
    carrito_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad INT4 NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_carrito_detalle PRIMARY KEY (carrito_id, producto_id),
    CONSTRAINT fk_carrito_detalle
        FOREIGN KEY (carrito_id)
        REFERENCES pedidos.carrito_de_compra (carrito_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_carrito_cantidad_positiva CHECK (cantidad > 0)
);

-- El esquema inicial conservaba solo la identidad mínima requerida por los
-- demás dominios. Estas columnas completan el modelo canónico de Usuarios.
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS cedula STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS telefono STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS usuario STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS contrasenia STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS usuario_bd STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS contrasenia_bd STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS metodopago_id INT8;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS rol_id INT8;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS avatar_path STRING;
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_login ON usuarios.usuario (usuario);

CREATE TABLE IF NOT EXISTS usuarios.rol (
    rol_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre STRING NOT NULL UNIQUE,
    habilitado BOOL NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS usuarios.provincia (
    provincia_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS usuarios.ciudad (
    ciudad_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre STRING NOT NULL,
    provincia_id INT8 NOT NULL REFERENCES usuarios.provincia (provincia_id),
    habilitado BOOL NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS usuarios.direccion (
    direccion_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle STRING NOT NULL,
    referencia STRING,
    habilitado BOOL NOT NULL DEFAULT true,
    usuario_id INT8 NOT NULL REFERENCES usuarios.usuario (usuario_id),
    ciudad_id INT8 NOT NULL REFERENCES usuarios.ciudad (ciudad_id),
    INDEX idx_direccion_usuario (usuario_id, habilitado)
);

CREATE TABLE IF NOT EXISTS usuarios.usuario_auditoria (
    id_sesion INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT8 NOT NULL REFERENCES usuarios.usuario (usuario_id),
    ip STRING NOT NULL,
    nombre_ordenador STRING NOT NULL,
    fecha_login TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_ultima TIMESTAMPTZ,
    cerrada BOOL
);

CREATE TABLE IF NOT EXISTS usuarios.auth_refresh_tokens (
    jti UUID PRIMARY KEY,
    user_id INT8 NOT NULL REFERENCES usuarios.usuario (usuario_id),
    role STRING NOT NULL,
    family_id UUID NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    absolute_exp TIMESTAMPTZ NOT NULL,
    revoked BOOL NOT NULL DEFAULT false,
    INDEX idx_refresh_user (user_id, revoked)
);

CREATE TABLE IF NOT EXISTS productos.categoria_producto (
    id_categoria INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    obligatoria_pc BOOL NOT NULL DEFAULT false,
    peso_presupuesto DECIMAL(5,4) NOT NULL DEFAULT 0,
    CONSTRAINT pk_categoria_producto PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_producto_nombre UNIQUE (nombre),
    CONSTRAINT ck_categoria_peso CHECK (peso_presupuesto BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS productos.marca (
    marca_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_marca PRIMARY KEY (marca_id),
    CONSTRAINT uq_marca_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS productos.gama (
    gama_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    tipo_gama STRING NOT NULL,
    precio_ensamblado DECIMAL(18,2) NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_gama PRIMARY KEY (gama_id)
);

CREATE TABLE IF NOT EXISTS productos.iva (
    iva_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    porcentaje DECIMAL(5,2) NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_iva PRIMARY KEY (iva_id)
);

-- PostgreSQL usaba herencia para nueve tablas de subtipo. CockroachDB no
-- implementa herencia de tablas; los campos variables se conservan en JSONB.
CREATE TABLE IF NOT EXISTS productos.producto (
    producto_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    preciounitario DECIMAL(18,2) NOT NULL,
    enlace STRING,
    fecha DATE,
    stock INT4 NOT NULL DEFAULT 0,
    marca_id INT8 NOT NULL,
    gama_id INT8,
    iva_id INT8 NOT NULL,
    costo DECIMAL(18,2) NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    categoria_id INT8,
    valor_inventario DECIMAL(18,2) NOT NULL DEFAULT 0,
    atributos JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT pk_producto PRIMARY KEY (producto_id),
    CONSTRAINT uq_producto_nombre UNIQUE (nombre),
    CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id) REFERENCES productos.marca (marca_id),
    CONSTRAINT fk_producto_gama FOREIGN KEY (gama_id) REFERENCES productos.gama (gama_id),
    CONSTRAINT fk_producto_iva FOREIGN KEY (iva_id) REFERENCES productos.iva (iva_id),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id)
        REFERENCES productos.categoria_producto (id_categoria),
    CONSTRAINT ck_producto_precio CHECK (preciounitario >= 0),
    CONSTRAINT ck_producto_costo CHECK (costo >= 0),
    CONSTRAINT ck_producto_stock CHECK (stock >= 0),
    INDEX idx_producto_categoria (categoria_id, habilitado),
    INDEX idx_producto_fecha (fecha DESC)
);

CREATE TABLE IF NOT EXISTS productos.galeria_productos_v2 (
    galeria_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    producto_id INT8 NOT NULL,
    descripcion STRING,
    habilitado BOOL NOT NULL DEFAULT true,
    es_portada BOOL NOT NULL DEFAULT false,
    para_galeria BOOL NOT NULL DEFAULT true,
    para_menu BOOL NOT NULL DEFAULT false,
    posicion_galeria INT4,
    posicion_menu INT4,
    mime_type STRING,
    peso_bytes INT8,
    ancho INT4,
    alto INT4,
    hash_sha256 BYTES,
    contenido BYTES NOT NULL,
    CONSTRAINT pk_galeria_producto PRIMARY KEY (galeria_id),
    CONSTRAINT fk_galeria_producto FOREIGN KEY (producto_id)
        REFERENCES productos.producto (producto_id) ON DELETE CASCADE,
    INDEX idx_galeria_producto (producto_id, habilitado)
);

CREATE TABLE IF NOT EXISTS inventario.tipo_movimiento (
    tipo_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    CONSTRAINT pk_tipo_movimiento PRIMARY KEY (tipo_id),
    CONSTRAINT uq_tipo_movimiento_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS inventario.subtipo_movimiento (
    subtipo_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    tipo_id INT8 NOT NULL,
    CONSTRAINT pk_subtipo_movimiento PRIMARY KEY (subtipo_id),
    CONSTRAINT uq_subtipo_movimiento_nombre UNIQUE (nombre),
    CONSTRAINT fk_subtipo_tipo FOREIGN KEY (tipo_id)
        REFERENCES inventario.tipo_movimiento (tipo_id)
);

CREATE TABLE IF NOT EXISTS inventario.inventario_producto (
    producto_id INT8 NOT NULL,
    nombre STRING NOT NULL,
    stock INT4 NOT NULL DEFAULT 0,
    stock_minimo INT4 NOT NULL DEFAULT 0,
    costo DECIMAL(18,2) NOT NULL DEFAULT 0,
    precio_referencia DECIMAL(18,2) NOT NULL DEFAULT 0,
    habilitado BOOL NOT NULL DEFAULT true,
    valor_inventario DECIMAL(18,2) NOT NULL DEFAULT 0,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_inventario_producto PRIMARY KEY (producto_id),
    CONSTRAINT ck_inventario_stock CHECK (stock >= 0),
    CONSTRAINT ck_inventario_costo CHECK (costo >= 0)
);

CREATE TABLE IF NOT EXISTS inventario.movimiento_inventario (
    movimiento_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
    cantidad INT4 NOT NULL,
    costo_unitario DECIMAL(18,2),
    costo_total DECIMAL(18,2),
    referencia STRING,
    observacion STRING,
    producto_id INT8 NOT NULL,
    subtipo_id INT8 NOT NULL,
    CONSTRAINT pk_movimiento_inventario PRIMARY KEY (movimiento_id),
    CONSTRAINT fk_movimiento_subtipo FOREIGN KEY (subtipo_id)
        REFERENCES inventario.subtipo_movimiento (subtipo_id),
    INDEX idx_movimiento_producto_fecha (producto_id, fecha DESC)
);

CREATE TABLE IF NOT EXISTS inventario.solicitud_idempotente (
    clave VARCHAR(200) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_solicitud_idempotente PRIMARY KEY (clave)
);

CREATE TABLE IF NOT EXISTS inventario.kardex_inventario (
    kardex_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
    tipo_operacion STRING NOT NULL,
    cantidad_entrada INT4 NOT NULL DEFAULT 0,
    costo_unitario_entrada DECIMAL(18,2),
    costo_total_entrada DECIMAL(18,2),
    cantidad_salida INT4 NOT NULL DEFAULT 0,
    costo_unitario_salida DECIMAL(18,2),
    costo_total_salida DECIMAL(18,2),
    saldo_cantidad INT4 NOT NULL,
    saldo_costo_unitario DECIMAL(18,2) NOT NULL,
    saldo_total DECIMAL(18,2) NOT NULL,
    producto_id INT8 NOT NULL,
    CONSTRAINT pk_kardex_inventario PRIMARY KEY (kardex_id),
    INDEX idx_kardex_producto_fecha (producto_id, fecha DESC)
);

-- Reserva de stock con reloj Lamport. Agregadas aqui (punto 5, segunda
-- ronda) tras descubrir que este archivo nunca las tuvo: las creaba
-- InventarioSchemaInitializer.java por codigo (@PostConstruct), al margen
-- tanto de este esquema monolitico como de Flyway. Al eliminarse esa clase
-- (su reemplazo real es inventario-service/.../V3__reserva_stock_lamport.sql),
-- este archivo se habia quedado con 33 tablas mientras el sistema real ya
-- tiene 35 -- una divergencia real entre las dos definiciones del esquema,
-- no solo cosmetica, porque docker-compose.db.yml (el entorno de
-- evidencias de planes de consulta de la Entrega 4) aplica este archivo
-- solo y se quedaba sin estas dos tablas. Contenido identico al de la V3.
CREATE TABLE IF NOT EXISTS inventario.reserva_stock (
    carrito_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    usuario_id INT8 NOT NULL,
    cantidad INT4 NOT NULL CHECK (cantidad >= 0),
    lamport INT8 NOT NULL,
    dispositivo_id VARCHAR(100) NOT NULL,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (carrito_id, producto_id)
);
CREATE INDEX IF NOT EXISTS idx_reserva_stock_producto ON inventario.reserva_stock (producto_id);

CREATE TABLE IF NOT EXISTS inventario.operacion_reserva (
    operacion_id UUID PRIMARY KEY,
    carrito_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    aceptada BOOL NOT NULL,
    cantidad_reservada INT4 NOT NULL,
    stock_disponible INT4 NOT NULL,
    lamport INT8 NOT NULL,
    dispositivo_ganador VARCHAR(100) NOT NULL,
    mensaje VARCHAR(300) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ordenes_proveedores.proveedor (
    proveedor_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    ruc STRING NOT NULL,
    contacto_nombre STRING,
    telefono STRING,
    correo STRING,
    direccion STRING,
    activo BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_proveedor PRIMARY KEY (proveedor_id),
    CONSTRAINT uq_proveedor_ruc UNIQUE (ruc)
);

CREATE TABLE IF NOT EXISTS ordenes_proveedores.orden_compra (
    orden_compra_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    proveedor_id INT8 NOT NULL,
    usuario_id INT8 NOT NULL,
    numero_orden STRING UNIQUE,
    fecha_emision DATE NOT NULL DEFAULT current_date(),
    fecha_esperada DATE,
    fecha_recepcion DATE,
    estado STRING NOT NULL DEFAULT 'PENDIENTE',
    subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    iva DECIMAL(18,2) NOT NULL DEFAULT 0,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_orden_compra PRIMARY KEY (orden_compra_id),
    CONSTRAINT fk_orden_compra_proveedor FOREIGN KEY (proveedor_id)
        REFERENCES ordenes_proveedores.proveedor (proveedor_id),
    CONSTRAINT ck_orden_compra_estado CHECK (estado IN
        ('PENDIENTE', 'ENVIADA', 'RECIBIDA_PARCIAL', 'RECIBIDA', 'CANCELADA')),
    INDEX idx_orden_compra_estado_fecha (estado, fecha_emision DESC)
);

CREATE TABLE IF NOT EXISTS ordenes_proveedores.detalle_orden_compra (
    detalle_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_compra_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad_pedida INT4 NOT NULL,
    cantidad_recibida INT4 NOT NULL DEFAULT 0,
    costo_unitario DECIMAL(18,2) NOT NULL,
    subtotal_linea DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_detalle_orden_compra PRIMARY KEY (detalle_id),
    CONSTRAINT uq_detalle_orden_producto UNIQUE (orden_compra_id, producto_id),
    CONSTRAINT fk_detalle_orden FOREIGN KEY (orden_compra_id)
        REFERENCES ordenes_proveedores.orden_compra (orden_compra_id) ON DELETE CASCADE,
    CONSTRAINT ck_detalle_cantidad CHECK (cantidad_pedida > 0),
    CONSTRAINT ck_detalle_recibida CHECK
        (cantidad_recibida >= 0 AND cantidad_recibida <= cantidad_pedida),
    CONSTRAINT ck_detalle_costo CHECK (costo_unitario >= 0)
);

CREATE TABLE IF NOT EXISTS pedidos.tipo_metodopago (
    tipo_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_metodopago PRIMARY KEY (tipo_id),
    CONSTRAINT uq_tipo_metodopago_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS pedidos.metodopago (
    metodopago_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    numero_tarjeta STRING,
    fecha_expiracion DATE,
    habilitado BOOL NOT NULL DEFAULT true,
    tipo_id INT8 NOT NULL,
    usuario_id INT8 NOT NULL,
    CONSTRAINT pk_metodopago PRIMARY KEY (metodopago_id),
    CONSTRAINT fk_metodopago_tipo
        FOREIGN KEY (tipo_id) REFERENCES pedidos.tipo_metodopago (tipo_id),
    INDEX idx_metodopago_usuario (usuario_id, habilitado)
);

-- Fila aislada para demostrar de forma controlada una colision SERIALIZABLE.
-- No participa en el flujo funcional ni altera datos de negocio.
CREATE TABLE IF NOT EXISTS pedidos.retry_probe (
    probe_id INT8 NOT NULL,
    valor INT8 NOT NULL DEFAULT 0,
    CONSTRAINT pk_retry_probe PRIMARY KEY (probe_id)
);
UPSERT INTO pedidos.retry_probe (probe_id, valor) VALUES (1, 0);

CREATE TABLE IF NOT EXISTS pedidos.detalle_orden (
    fecha DATE NOT NULL,
    detalle_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad INT4 NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    iva DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_detalle_orden PRIMARY KEY (fecha, detalle_id),
    CONSTRAINT fk_detalle_orden
        FOREIGN KEY (fecha, orden_id)
        REFERENCES pedidos.orden (fecha, orden_id),
    CONSTRAINT ck_detalle_cantidad_positiva CHECK (cantidad > 0),
    INDEX idx_detalle_orden (fecha, orden_id),
    INDEX idx_detalle_producto_fecha (producto_id, fecha DESC)
);

CREATE TABLE IF NOT EXISTS pedidos.solicitud_idempotente (
     usuario_id    INT8        NOT NULL,
     clave         VARCHAR     NOT NULL,
     payload_hash  VARCHAR     NOT NULL,
     orden_id      INT8        NOT NULL,
     creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_solicitud_idempotente PRIMARY KEY (usuario_id, clave),
    CONSTRAINT fk_solicitud_idempotente_orden
    FOREIGN KEY (orden_id) REFERENCES pedidos.orden (orden_id)
);

CREATE TABLE IF NOT EXISTS ventas.factura_encabezado (
    factura_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_id INT8 NOT NULL,
    fecha_orden DATE NOT NULL,
    usuario_id INT8 NOT NULL,
    fecha_emision DATE NOT NULL DEFAULT current_date(),
    cedula STRING,
    nombre STRING,
    correo STRING,
    telefono STRING,
    direccion_entrega STRING,
    subtotal DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    numero STRING NOT NULL,
    CONSTRAINT pk_factura PRIMARY KEY (factura_id),
    CONSTRAINT uq_factura_orden UNIQUE (orden_id),
    CONSTRAINT uq_factura_numero UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS ventas.factura_cuerpo (
    factura_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    nombre_producto STRING NOT NULL,
    cantidad INT4 NOT NULL,
    precio DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    iva DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_factura_cuerpo PRIMARY KEY (factura_id, producto_id),
    CONSTRAINT fk_factura_cuerpo
        FOREIGN KEY (factura_id)
        REFERENCES ventas.factura_encabezado (factura_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ventas.factura_outbox (
    evento_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    factura_id INT8 NOT NULL,
    estado STRING NOT NULL DEFAULT 'PENDIENTE',
    intentos INT4 NOT NULL DEFAULT 0,
    ultimo_error STRING,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    procesado_en TIMESTAMPTZ,
    CONSTRAINT pk_factura_outbox PRIMARY KEY (evento_id),
    CONSTRAINT uq_factura_outbox_factura UNIQUE (factura_id),
    CONSTRAINT fk_factura_outbox_factura
        FOREIGN KEY (factura_id) REFERENCES ventas.factura_encabezado (factura_id),
    CONSTRAINT ck_factura_outbox_estado CHECK (estado IN ('PENDIENTE', 'PROCESADO', 'FALLIDO')),
    INDEX idx_factura_outbox_estado (estado, creado_en)
);

-- Fragmentación horizontal física por límites trimestrales. SPLIT AT crea
-- límites de rango reproducibles sin requerir una licencia Enterprise.
ALTER TABLE pedidos.orden SPLIT AT VALUES
    ('2026-01-01'),
    ('2026-04-01'),
    ('2026-07-01'),
    ('2026-10-01'),
    ('2027-01-01');

ALTER TABLE pedidos.detalle_orden SPLIT AT VALUES
    ('2026-01-01'),
    ('2026-04-01'),
    ('2026-07-01'),
    ('2026-10-01'),
    ('2027-01-01');

ALTER TABLE pedidos.orden SCATTER;
ALTER TABLE pedidos.detalle_orden SCATTER;

-- Replicacion de tres copias: con quorum mayoritario, el rango tolera
-- la perdida de una replica. La prueba con dos nodos debe perder disponibilidad.
ALTER RANGE default CONFIGURE ZONE USING num_replicas = 3;

-- Consultas de referencia para el protocolo experimental.
-- Top-N de productos por trimestre:
-- SELECT producto_id, sum(cantidad) AS unidades
-- FROM pedidos.detalle_orden
-- WHERE fecha >= $1 AND fecha < $2
-- GROUP BY producto_id
-- ORDER BY unidades DESC
-- LIMIT 10;
--
-- Historial colocalizable por el indice (usuario_id, fecha):
-- SELECT fecha, orden_id, estado, total
-- FROM pedidos.orden
-- WHERE usuario_id = $1
-- ORDER BY fecha DESC;
