global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tiendatech-java-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - tiendatech-productos:8081
          - tiendatech-inventario:8082
          - tiendatech-pedidos:8083
          - tiendatech-ordenes-proveedores:8084
          - tiendatech-usuarios:8085
          - tiendatech-ventas:8086
          - tiendatech-gateway:8080
  - job_name: tiendatech-armado-ia
    metrics_path: /metrics
    static_configs:
      - targets: [tiendatech-armado-ia:8087]
