-- Migracion base del esquema `productos`, extraida de docs/db/schema.sql
-- (monolito original) al dividir por servicio propietario. Contenido
-- identico al de esa fuente para las tablas de este esquema.

CREATE SCHEMA IF NOT EXISTS productos;

CREATE TABLE IF NOT EXISTS productos.categoria_producto (
    id_categoria INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    obligatoria_pc BOOL NOT NULL DEFAULT false,
    peso_presupuesto DECIMAL(5,4) NOT NULL DEFAULT 0,
    CONSTRAINT pk_categoria_producto PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_producto_nombre UNIQUE (nombre),
    CONSTRAINT ck_categoria_peso CHECK (peso_presupuesto BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS productos.marca (
    marca_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_marca PRIMARY KEY (marca_id),
    CONSTRAINT uq_marca_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS productos.gama (
    gama_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    tipo_gama STRING NOT NULL,
    precio_ensamblado DECIMAL(18,2) NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_gama PRIMARY KEY (gama_id)
);

CREATE TABLE IF NOT EXISTS productos.iva (
    iva_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    porcentaje DECIMAL(5,2) NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    CONSTRAINT pk_iva PRIMARY KEY (iva_id)
);

-- PostgreSQL usaba herencia para nueve tablas de subtipo. CockroachDB no
-- implementa herencia de tablas; los campos variables se conservan en JSONB.
CREATE TABLE IF NOT EXISTS productos.producto (
    producto_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    preciounitario DECIMAL(18,2) NOT NULL,
    enlace STRING,
    fecha DATE,
    stock INT4 NOT NULL DEFAULT 0,
    marca_id INT8 NOT NULL,
    gama_id INT8,
    iva_id INT8 NOT NULL,
    costo DECIMAL(18,2) NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    categoria_id INT8,
    valor_inventario DECIMAL(18,2) NOT NULL DEFAULT 0,
    atributos JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT pk_producto PRIMARY KEY (producto_id),
    CONSTRAINT uq_producto_nombre UNIQUE (nombre),
    CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id) REFERENCES productos.marca (marca_id),
    CONSTRAINT fk_producto_gama FOREIGN KEY (gama_id) REFERENCES productos.gama (gama_id),
    CONSTRAINT fk_producto_iva FOREIGN KEY (iva_id) REFERENCES productos.iva (iva_id),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id)
        REFERENCES productos.categoria_producto (id_categoria),
    CONSTRAINT ck_producto_precio CHECK (preciounitario >= 0),
    CONSTRAINT ck_producto_costo CHECK (costo >= 0),
    CONSTRAINT ck_producto_stock CHECK (stock >= 0),
    INDEX idx_producto_categoria (categoria_id, habilitado),
    INDEX idx_producto_fecha (fecha DESC)
);

CREATE TABLE IF NOT EXISTS productos.galeria_productos_v2 (
    galeria_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    producto_id INT8 NOT NULL,
    descripcion STRING,
    habilitado BOOL NOT NULL DEFAULT true,
    es_portada BOOL NOT NULL DEFAULT false,
    para_galeria BOOL NOT NULL DEFAULT true,
    para_menu BOOL NOT NULL DEFAULT false,
    posicion_galeria INT4,
    posicion_menu INT4,
    mime_type STRING,
    peso_bytes INT8,
    ancho INT4,
    alto INT4,
    hash_sha256 BYTES,
    contenido BYTES NOT NULL,
    CONSTRAINT pk_galeria_producto PRIMARY KEY (galeria_id),
    CONSTRAINT fk_galeria_producto FOREIGN KEY (producto_id)
        REFERENCES productos.producto (producto_id) ON DELETE CASCADE,
    INDEX idx_galeria_producto (producto_id, habilitado)
);
