-- Migracion base del esquema `usuarios`, extraida de docs/db/schema.sql
-- (monolito original) al dividir por servicio propietario. Contenido
-- identico al de esa fuente para las tablas de este esquema; no se
-- modifica ninguna definicion.

CREATE SCHEMA IF NOT EXISTS usuarios;

CREATE TABLE IF NOT EXISTS usuarios.usuario (
    usuario_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    correo STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_correo UNIQUE (correo)
);

-- El esquema inicial conservaba solo la identidad minima requerida por los
-- demas dominios. Estas columnas completan el modelo canonico de Usuarios.
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS cedula STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS telefono STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS usuario STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS contrasenia STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS usuario_bd STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS contrasenia_bd STRING;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS metodopago_id INT8;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS rol_id INT8;
ALTER TABLE usuarios.usuario ADD COLUMN IF NOT EXISTS avatar_path STRING;
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_login ON usuarios.usuario (usuario);

CREATE TABLE IF NOT EXISTS usuarios.rol (
    rol_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre STRING NOT NULL UNIQUE,
    habilitado BOOL NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS usuarios.provincia (
    provincia_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS usuarios.ciudad (
    ciudad_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre STRING NOT NULL,
    provincia_id INT8 NOT NULL REFERENCES usuarios.provincia (provincia_id),
    habilitado BOOL NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS usuarios.direccion (
    direccion_id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle STRING NOT NULL,
    referencia STRING,
    habilitado BOOL NOT NULL DEFAULT true,
    usuario_id INT8 NOT NULL REFERENCES usuarios.usuario (usuario_id),
    ciudad_id INT8 NOT NULL REFERENCES usuarios.ciudad (ciudad_id),
    INDEX idx_direccion_usuario (usuario_id, habilitado)
);

CREATE TABLE IF NOT EXISTS usuarios.usuario_auditoria (
    id_sesion INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT8 NOT NULL REFERENCES usuarios.usuario (usuario_id),
    ip STRING NOT NULL,
    nombre_ordenador STRING NOT NULL,
    fecha_login TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_ultima TIMESTAMPTZ,
    cerrada BOOL
);

CREATE TABLE IF NOT EXISTS usuarios.auth_refresh_tokens (
    jti UUID PRIMARY KEY,
    user_id INT8 NOT NULL REFERENCES usuarios.usuario (usuario_id),
    role STRING NOT NULL,
    family_id UUID NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    absolute_exp TIMESTAMPTZ NOT NULL,
    revoked BOOL NOT NULL DEFAULT false,
    INDEX idx_refresh_user (user_id, revoked)
);
